targets:
  fifty: [fifty/common_voice_en_18311788.wav, fifty/common_voice_en_221716.wav, fifty/common_voice_en_592641.wav,
    fifty/common_voice_en_618164.wav, fifty/common_voice_en_18319723.wav, fifty/common_voice_en_58527.wav,
    fifty/common_voice_en_547040.wav, fifty/common_voice_en_589795.wav, fifty/common_voice_en_18584035.wav,
    fifty/common_voice_en_654833.wav, fifty/common_voice_en_569829.wav, fifty/common_voice_en_164736.wav,
    fifty/common_voice_en_204367.wav, fifty/common_voice_en_557855.wav, fifty/common_voice_en_18489252.wav,
    fifty/common_voice_en_22442160.wav, fifty/common_voice_en_549631.wav, fifty/common_voice_en_545027.wav,
    fifty/common_voice_en_18508306.wav, fifty/common_voice_en_58134.wav, fifty/common_voice_en_517644.wav]
  episode: [episode/common_voice_en_19991795.wav, episode/common_voice_en_21282560.wav,
    episode/common_voice_en_19421086.wav, episode/common_voice_en_19363133__2.wav,
    episode/common_voice_en_21518222.wav, episode/common_voice_en_18974258.wav, episode/common_voice_en_18890749.wav,
    episode/common_voice_en_18769857.wav, episode/common_voice_en_21087884.wav, episode/common_voice_en_21596054.wav,
    episode/common_voice_en_20781232.wav, episode/common_voice_en_20583224.wav, episode/common_voice_en_21755041.wav,
    episode/common_voice_en_20990177.wav]
  job: [job/common_voice_en_613466.wav, job/common_voice_en_55565.wav, job/common_voice_en_219427.wav,
    job/common_voice_en_604466.wav, job/common_voice_en_21019713.wav, job/common_voice_en_598671.wav,
    job/common_voice_en_676857.wav, job/common_voice_en_20245239.wav, job/common_voice_en_18148688.wav,
    job/common_voice_en_18661396.wav, job/common_voice_en_669885.wav, job/common_voice_en_9074.wav,
    job/common_voice_en_208591.wav, job/common_voice_en_483197.wav, job/common_voice_en_218560.wav,
    job/common_voice_en_668684.wav, job/common_voice_en_185643.wav, job/common_voice_en_687140.wav,
    job/common_voice_en_527903.wav, job/common_voice_en_679918.wav, job/common_voice_en_500663.wav,
    job/common_voice_en_509288.wav, job/common_voice_en_19620824.wav, job/common_voice_en_19628977.wav,
    job/common_voice_en_95702.wav, job/common_voice_en_18066750.wav, job/common_voice_en_674788.wav,
    job/common_voice_en_8669.wav, job/common_voice_en_18761785.wav, job/common_voice_en_18143386.wav,
    job/common_voice_en_20519834.wav, job/common_voice_en_20644225.wav]
  route: [route/common_voice_en_19369483.wav, route/common_voice_en_21450014.wav,
    route/common_voice_en_21798199.wav, route/common_voice_en_20446122.wav, route/common_voice_en_20301542.wav,
    route/common_voice_en_22361257.wav, route/common_voice_en_20997573.wav, route/common_voice_en_18778659.wav,
    route/common_voice_en_21384972.wav, route/common_voice_en_20008500.wav, route/common_voice_en_21913895.wav,
    route/common_voice_en_19945977.wav, route/common_voice_en_21513761.wav, route/common_voice_en_19815852.wav,
    route/common_voice_en_513685.wav, route/common_voice_en_21573329.wav]
  restaurant: [restaurant/common_voice_en_658866.wav, restaurant/common_voice_en_18580081.wav,
    restaurant/common_voice_en_20313764.wav, restaurant/common_voice_en_650570.wav,
    restaurant/common_voice_en_166077.wav, restaurant/common_voice_en_18686906.wav,
    restaurant/common_voice_en_616538.wav, restaurant/common_voice_en_689428.wav,
    restaurant/common_voice_en_20235696.wav, restaurant/common_voice_en_513566.wav,
    restaurant/common_voice_en_19763634.wav, restaurant/common_voice_en_586993.wav,
    restaurant/common_voice_en_19960484__2.wav, restaurant/common_voice_en_19634743.wav,
    restaurant/common_voice_en_20376186.wav, restaurant/common_voice_en_516121.wav,
    restaurant/common_voice_en_162728.wav]
nontargets: [municipality/common_voice_en_19118375.wav, shoulder/common_voice_en_103233.wav,
  plain/common_voice_en_19821646.wav, telescope/common_voice_en_20424734.wav, powers/common_voice_en_19975284.wav,
  brief/common_voice_en_17273524.wav, historic/common_voice_en_18753171.wav, dead/common_voice_en_19047013.wav,
  each/common_voice_en_18794358.wav, direct/common_voice_en_19471390.wav, item/common_voice_en_16048248.wav,
  teaches/common_voice_en_19359038.wav, tunnel/common_voice_en_19238711.wav, grand/common_voice_en_18034433.wav,
  item/common_voice_en_18518380.wav, participated/common_voice_en_18860865.wav, direct/common_voice_en_20325427.wav,
  crops/common_voice_en_18788890.wav, tom/common_voice_en_17252751.wav, tribal/common_voice_en_45941.wav]
